### ISSUE TITLE
サポートチャットで「Send」を押下したあとの挙動

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-web-admin#16]
・投稿した内容F5キーなどでリロードしないとチャットウインドウに表示されない。
・入力欄から投稿済の内容が消えず、連続して投稿する場合は、入力内容を消す必要がある。

以上の状況により、投稿が完了できたか分かり辛い。

**Comment by yoneyan** [comment]
debea6b にて修正
