### ISSUE TITLE
Connectionの詳細情報で「Route」の情報が表示されない

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-web-admin#5]
希望する経路やプロトコル（Route）の情報が空白になり表示されない
![image](https://user-images.githubusercontent.com/19766266/102092278-3d88ec00-3e63-11eb-9a1c-2e3eef67abbc.png)

**Comment by yoneyan** [comment]
ba62e95a92763611bb19e3e4eb60a59aaf3df792　にて修正済み
