### ISSUE TITLE
管理画面で接続情報の追加をす際、BGPの経路広報に関する不具合

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-web-admin#76]
１．日本語が不適切
「1.1. 広報するBGPの方法を選択してください。」と記載があるが、
「BGPで当団体から広報する経路種類を選択してください」が正しいと思う。

2. フルルートの他の選択肢が「Static Route」になっている。
　Default Route が正しいと思う。

3. フルルートとデフォルトルート以外の選択肢が無い
　「その他」といったような選択肢が必要そうである。

**Comment by yoneyan** [comment]
3に関してはその他の項目のみ作る(コメント機能は不要)

**Comment by yoneyan** [comment]
項目2,3に関してはDBを修正、追加したため修正完了

**Comment by yoneyan** [comment]
d7a518d にて修正
